import { inflateRawSync } from 'node:zlib';

type ZipEntry={name:string;compression:number;compressedSize:number;uncompressedSize:number;offset:number};
export type SpreadsheetRow={lineNumber:number;raw:Record<string,unknown>};

function xmlDecode(value:string){return value.replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&quot;/g,'"').replace(/&apos;/g,"'").replace(/&amp;/g,'&');}
function attrs(value:string){const result:Record<string,string>={};for(const match of value.matchAll(/([A-Za-z_:][\w:.-]*)="([^"]*)"/g))result[match[1]??'']=xmlDecode(match[2]??'');return result;}
function entries(buffer:Buffer){const result:ZipEntry[]=[];let cursor=buffer.lastIndexOf(Buffer.from([0x50,0x4b,0x05,0x06]));if(cursor<0)cursor=buffer.length-22;const centralOffset=buffer.readUInt32LE(cursor+16);const centralSize=buffer.readUInt32LE(cursor+12);let position=centralOffset;const end=centralOffset+centralSize;while(position<end&&buffer.readUInt32LE(position)===0x02014b50){const compression=buffer.readUInt16LE(position+10);const compressedSize=buffer.readUInt32LE(position+20);const uncompressedSize=buffer.readUInt32LE(position+24);const nameLength=buffer.readUInt16LE(position+28);const extraLength=buffer.readUInt16LE(position+30);const commentLength=buffer.readUInt16LE(position+32);const offset=buffer.readUInt32LE(position+42);const name=buffer.subarray(position+46,position+46+nameLength).toString('utf8');result.push({name,compression,compressedSize,uncompressedSize,offset});position+=46+nameLength+extraLength+commentLength;}return result;}
function readZip(buffer:Buffer,name:string){const entry=entries(buffer).find(item=>item.name===name);if(!entry) return undefined;const localNameLength=buffer.readUInt16LE(entry.offset+26);const localExtraLength=buffer.readUInt16LE(entry.offset+28);const start=entry.offset+30+localNameLength+localExtraLength;const compressed=buffer.subarray(start,start+entry.compressedSize);if(entry.compression===0)return compressed;if(entry.compression===8)return inflateRawSync(compressed);throw new Error(`Compresión XLSX no soportada para ${name}`);}
function textFromXml(value:string){return xmlDecode(value.replace(/<[^>]+>/g,''));}
function sharedStrings(xml:string){return[...xml.matchAll(/<si>([\s\S]*?)<\/si>/g)].map(match=>[...((match[1]??'').matchAll(/<t[^>]*>([\s\S]*?)<\/t>/g))].map(item=>textFromXml(item[1]??'')).join(''));}
function columnNumber(ref:string){let number=0;for(const char of ref){if(char<'A'||char>'Z')break;number=number*26+char.charCodeAt(0)-64;}return number-1;}
function serialDate(value:number){const date=new Date(Date.UTC(1899,11,30)+Math.round(value*86_400_000));return`${date.getUTCFullYear()}-${String(date.getUTCMonth()+1).padStart(2,'0')}-${String(date.getUTCDate()).padStart(2,'0')}`;}
function cellValue(cell:string,shared:string[]){const attributes=attrs(cell.slice(0,cell.indexOf('>')+1));const type=attributes.t;const inline=cell.match(/<is>[\s\S]*?<t[^>]*>([\s\S]*?)<\/t>[\s\S]*?<\/is>/)?.[1];const value=cell.match(/<v[^>]*>([\s\S]*?)<\/v>/)?.[1]??inline??'';const decoded=textFromXml(value);if(type==='s')return shared[Number(decoded)]??'';if(type==='b')return decoded==='1';if(type==='inlineStr')return decoded;const number=Number(decoded);return decoded!==''&&Number.isFinite(number)?number:decoded;}
export function parseXlsx(buffer:Buffer):{headers:string[];rows:SpreadsheetRow[]}{const workbookXml=readZip(buffer,'xl/workbook.xml')?.toString('utf8')??'';const relationshipXml=readZip(buffer,'xl/_rels/workbook.xml.rels')?.toString('utf8')??'';const firstSheet=workbookXml.match(/<sheet[^>]*r:id="([^"]+)"[^>]*>/)?.[1]??'rId1';const target=relationshipXml.match(new RegExp(`<Relationship[^>]*Id="${firstSheet}"[^>]*Target="([^"]+)"`))?.[1]??'worksheets/sheet1.xml';const sheetName=target.startsWith('xl/')?target:`xl/${target}`;const sheetXml=readZip(buffer,sheetName)?.toString('utf8');if(!sheetXml)throw new Error('No fue posible leer la primera hoja del XLSX');const shared=sharedStrings(readZip(buffer,'xl/sharedStrings.xml')?.toString('utf8')??'');const rows=[...sheetXml.matchAll(/<row[^>]*r="(\d+)"[^>]*>([\s\S]*?)<\/row>/g)];const matrix:unknown[][]=[];for(const row of rows){const cells=[...((row[2]??'').matchAll(/<c\s[^>]*?(?:\/>|>[\s\S]*?<\/c>)/g))];const values:unknown[]=[];for(const cell of cells){const ref=cell[0].match(/\br="([A-Z]+)\d+"/)?.[1]??'';values[columnNumber(ref)]=cellValue(cell[0],shared);}matrix.push(values);}const headers=(matrix[0]??[]).map(value=>String(value??'').trim());const dateColumns=new Set(headers.map((header,index)=>/fecha|periodo\s*liq|vaca\.?\s*disfru/i.test(header)?index:-1).filter(index=>index>=0));const rowsOut:SpreadsheetRow[]=[];for(let index=1;index<matrix.length;index++){const values=matrix[index]??[];const raw:Record<string,unknown>={};headers.forEach((header,column)=>{if(!header)return;const value=values[column];raw[header]=dateColumns.has(column)&&typeof value==='number'?serialDate(value):value??'';});rowsOut.push({lineNumber:Number(rows[index]?.[1]??index+1),raw});}return{headers,rows:rowsOut};}
