import type { Employment } from '../workers/models.js';
import type { LocalDate } from '../shared/localDate.js';
import { addDays, addMonths, addYearsAnniversary, daysBetween } from '../shared/localDate.js';
import type { VacationPeriod, VacationPolicy } from './models.js';
export const RETIREMENT_CLOSURE_OBSERVATION = 'Cierre de vacaciones por terminación de contrato';
export function createPeriod(employment:Employment, sequence:number, start:LocalDate, policy:VacationPolicy, asOf:LocalDate):VacationPeriod { const causedAt=addYearsAnniversary(start,1); return {id:`${employment.id}-${sequence}`,employmentId:employment.id,sequence,accrualStartDate:start,accrualEndDate:addDays(causedAt,-1),causedAt,entitledDays:policy.daysPerCompletedYear,lifecycleStatus:causedAt<=asOf?'CAUSED':'FORMING',version:1,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()}; }
export function ensurePeriods(employment:Employment, existing:VacationPeriod[], policy:VacationPolicy, asOf:LocalDate):VacationPeriod[] { const periods=[...existing].sort((a,b)=>a.sequence-b.sequence); let sequence=periods.length?periods[periods.length-1]!.sequence+1:1; let start=periods.length?addYearsAnniversary(periods[periods.length-1]!.accrualStartDate,1):employment.startDate; const maximum=employment.endDate ?? asOf; while(start<=maximum){ const period=createPeriod(employment,sequence,start,policy,asOf); periods.push(period); sequence++; start=addYearsAnniversary(start,1); if(start>asOf && !employment.endDate) break; if(sequence>200) throw new Error('Period generation limit exceeded'); } return periods; }
export function closePeriodsAtRetirement(employment:Employment, periods:VacationPeriod[], now=new Date().toISOString()):VacationPeriod[] { if(employment.status!=='RETIRED'||!employment.endDate)return periods; return periods.map(period=>period.lifecycleStatus==='CLOSED'||period.pendingImportProtected?period:{...period,lifecycleStatus:'CLOSED',closureType:'RETIREMENT',closureObservation:RETIREMENT_CLOSURE_OBSERVATION,closedAt:now,closedBy:'system-retirement-closure',version:period.version+1,updatedAt:now}); }
export function pendingDays(period:VacationPeriod, settlements:VacationSettlementLike[]):number { const used=settlements.flatMap(s=>s.allocations.filter(a=>a.periodId===period.id)).reduce((n,a)=>n+a.enjoyedDays+a.compensatedDays,0); return Math.max(0,period.entitledDays-used); }
export interface VacationSettlementLike { allocations:{periodId:string; enjoyedDays:number; compensatedDays:number}[]; }
export function scheduledDays(period:VacationPeriod,schedules:VacationScheduleLike[]):number { return schedules.filter(s=>s.status==='SCHEDULED').flatMap(s=>s.allocations.filter(a=>a.periodId===period.id)).reduce((n,a)=>n+a.days,0); }
export interface VacationScheduleLike { status:string; allocations:{periodId?:string|undefined;days:number}[]; }
export function progress(period:VacationPeriod,asOf:LocalDate):number { const total=daysBetween(period.accrualStartDate,period.causedAt); const elapsed=Math.max(0,Math.min(total,daysBetween(period.accrualStartDate,asOf))); return Math.round(elapsed/total*100); }
export function overdue(period:VacationPeriod,pending:number,policy:VacationPolicy,asOf:LocalDate):boolean{return pending>0&&period.lifecycleStatus!=='FORMING'&&addMonths(period.causedAt,policy.overdueAfterMonths)<=asOf;}
export function alertFor(days:number):'NORMAL'|'INFORMATIVE'|'UPCOMING'|'DUE_SOON'|'CAUSED_TODAY'{if(days<=0)return'CAUSED_TODAY';if(days<=30)return'DUE_SOON';if(days<=60)return'UPCOMING';if(days<=90)return'INFORMATIVE';return'NORMAL'}
